services:
  garage:
    image: dxflrs/garage:v1.1.0
    container_name: inko-garage
    command: ["/garage", "server"]
    ports:
      - "3900:3900"
      - "3903:3903"
    volumes:
      - ./scripts/garage/garage.toml:/etc/garage.toml:ro
      - inko-garage-meta:/var/lib/garage/meta
      - inko-garage-data:/var/lib/garage/data
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  inko-garage-meta:
  inko-garage-data:
